### ISSUE TITLE
[macOS] [gain_gui] Wrong Cursor Position

### ISSUE THREAD

**Issue by apalm** [robbert-vdh/nih-plug#1]
OS: macOS 12.2.1
DAW: REAPER 6.49

First of all, thank you for building this framework. It looks very cool.

I wanted to try out `gain_gui`, so I built it using `cargo xtask bundle gain_gui --release --bundle-vst3`, then copied `target/gain_gui.vst3` to `/Library/Audio/Plug-Ins/VST3`.

While the plugin works, the cursor position appears to be off. This is most obvious with the slider, which isn't draggable unless I drag on a specific spot below the handle. Maybe a scaling issue?

https://user-images.githubusercontent.com/4495237/155819619-16238ac4-b580-4ccf-827a-3e09e10bee58.mov

I understand that this stuff hasn't been tested on macOS, so feel free to close this issue if it's not actionable :)

**Comment by apalm** [comment]
So, when creating my minimal repro, I noticed that if I used `WindowScalePolicy::ScaleFactor(1.0)`, I saw the same issue exhibited in `gain_gui`. However, when using `WindowScalePolicy::SystemScaleFactor`, the issue went away.

My minimal repro with `WindowScalePolicy::ScaleFactor(1.0)`:

https://user-images.githubusercontent.com/4495237/155869717-5055a6a2-3c9d-474c-b9da-8b539d8a83d3.mov

My minimal repro with `WindowScalePolicy::SystemScaleFactor`:

https://user-images.githubusercontent.com/4495237/155869696-8b734d16-6333-4385-a7e8-a384652e0099.mov

gain_gui with `WindowScalePolicy::SystemScaleFactor`:


https://user-images.githubusercontent.com/4495237/155869749-7adf381a-219a-461e-9bf0-bcdd16fc1a03.mov

Not sure if this is a `baseview` bug?

**Comment by robbert-vdh** [comment]
Ah, good catch. Macs with their HiDPI screens. :wink: 

Hadn't really considered HiDPI yet since baseview doesn't support window resizing (and I already have two open PRs there), but I'll  add this in the meantime. The host should be able to override this with `IPlugViewContentScaleSupport::setContentScaleFactor()` once that is in place. I added the change in b40c43a862b7361ae372cf4a0ed3e5aad710b68d.
