### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by jesses-code-adventures** [robbert-vdh/nih-plug#101]
Hey there,

When I build one of the example plugins (using cargo xtask bundle gain --release) and move the bundled vst3 into my plugins folder, my DAW fails to find the plugin. 

I suspect this is because I'm on osx 12.6 and I can see the targeted osx version in CI is 11, and understand that osx support is limited per the readme.

Would I be right about this or am I missing something else? My apologies for the elementary question & thank you!

**Comment by magwa101** [comment]
OSX 14 here and I get "<plugin>.clap was blocked from use because it is not from an identified developer." And if I click the provided button "Open Anyway" nothing happens. Just wondering if others see this and have a workaround.

**Comment by robbert-vdh** [comment]
@jesses-code-adventures Did you copy the plugin to the right location?

@magwa101 Follow the instructions from the readme on how to disable gatekeeper for the plugin.

Closing as there's nothing actionable here.

**Comment by jesses-code-adventures** [comment]
It's definitely in the same directory as the rest of my plugins, but I understand your time probably shouldn't be spent on such entry level problems - my apologies for the issue

**Comment by magwa101** [comment]
Yep, found it, thanks!

**Comment by magwa101** [comment]
I have removed the gatekeeper errors. I see this error in Bitwig, which
actually, I've always seen. Not sure if this is meaningful.

I'm using Mac Sonoma 14.2.1 and Bitwig 5.1.2.

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException:
could not read metadata: Could not load executable: The bundle couldn’t be
loaded.

Thanks
