### ISSUE TITLE
i cannot install it. i try to install spectral compressor for 4 hours and i got a really weird ui. why couldnt you just uploade the vst3 version or .clap version. many of us are no programmers

### ISSUE THREAD

**Issue by mrczorz** [robbert-vdh/nih-plug#120]
i cannot install it. i try to install spectral compressor for 4 hours and i got a really weird ui. why couldnt you just uploade the vst3 version or .clap version. many of us are no programmers

**Comment by robbert-vdh** [comment]
You can find downloads here: https://nightly.link/robbert-vdh/nih-plug/workflows/build/master

There's a readme file in the downloaded archive.
