### ISSUE TITLE
Spectral Compressor feature request

### ISSUE THREAD

**Issue by ZetKaySound** [robbert-vdh/nih-plug#126]
hy there and thanks for this great plugin, excuse me if my post is wrong here or executed wrong, pretty new here on github, signed just for that request.

i think it would be a cool feature to have adjustable high-/lowpass filters for the threshold curve in 6/12/24/48/96 db/octave slopes to just target specific ranges in the spectrum to archieve a more linear than bell shaped zone.

a global slope setting for the analyzer window also would be dope in +3db/oct.

thx in advance
Zag

**Comment by robbert-vdh** [comment]
The commercial version of the plugin will have freely drawable curves, but I have no time frame on when that's coming just yet.
