### ISSUE TITLE
Unable to build example plugins

### ISSUE THREAD

**Issue by ReedSchroeder** [robbert-vdh/nih-plug#128]
Apologies if this is not the place to post about this, but I have not found a link to a discord server or any other place to get help with this problem.

I have been trying to build the example plugins, but every time I get the following error:

> error: linker `link.exe` not found

I am using Windows 10. I installed rust and Visual Studio. 

Apologies if this is a basic question, but this is my first time doing anything in Rust.

**Comment by robbert-vdh** [comment]
You're probably missing part of the Visual Studio toolchain setup. Rustup should guide you through it. I can't really help you beyond that, sorry.

**Comment by arthurxmedic** [comment]
yeah no yeah, the plugins still break because of this
