### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by juanmartin** [robbert-vdh/nih-plug#131]
Hi!

I cannot see Puberty Simulator and Spectral Compressor in Ableton Live's 11 plug-in list.

I have removed the `com.apple.quarantine` attribute from all VST3 files and the rest of them are seen and work in my DAW.

Is there something I might be missing?

Thank you for everything!!!

**Comment by robbert-vdh** [comment]
If you tried to load them before disabling gatekeeper or removing the quarantine flag, you may need to completely remove the files first and then install the plugins again. MacOS seems to intentionally try to make these things as cumbersome as possible.

**Comment by juanmartin** [comment]
OK now it worked, thank you!

For future reference, these were the steps I took.

1. Downloaded using `curl -LO` from the latest [nightly link](https://nightly.link/robbert-vdh/nih-plug/workflows/build/master)
2. Did `xattr -rd com.apple.quarantine` to the zip, just in case
3. `unzip` the zip, `cd` into the folder
4. `xattr -rd com.apple.quarantine *`
5. Copied the plugin files to their respective folders in my case the usual `/Library/Audio/Plug-Ins/VST3` and CLAP folders
6. Launched DAW and all of them showed up.

Thanks again for the great work!
