### ISSUE TITLE
Opening 2 instances of Spectral Compressor crashes FL Studio 21

### ISSUE THREAD

**Issue by akasuu** [robbert-vdh/nih-plug#145]
Spectral Compressor 0.4.3
FL Studio 21.2.3
Windows 10 22H2

**Comment by robbert-vdh** [comment]
This should now be fixed as of 9e2b9cc06eace2f05d430661873202a2154d0f05. See the various duplicate issues (e.g. #129) for more information.

**Comment by akasuu** [comment]
THANK YOU SIR
