### ISSUE TITLE
Help with background tasks needed (no obvious example)

### ISSUE THREAD

**Issue by Timtam** [robbert-vdh/nih-plug#172]
Hello there,

i'm starting all fresh into the world of developing VST/CLAP plugins, and since Rust is currently my goto language of choice, I'd really like to take on the challenge with nih-plug.

My plugin idea requires to read incoming data (most likely via a separate background thread), and feed that data back via the main audio processing thread in nih-plug. I noticed that nih-plug offers support for background tasks via the BackgroundTask type, but all plugins, examples and full-featured ones, don't seem to use this one. I wasn't able to dig up an example that I could try to wrap my head around to get an idea how I can approach my problem.
Do you have any idea where I can take a look at?

Thank you.

**Comment by dathinaios** [comment]
Hello,

Just in case you are not aware the best place to ask questions is the Rust Audio discord. It has a channel for `nih-plug`. Here is an invite link:

https://discord.gg/7VpsKvA9

**Comment by ardura** [comment]
There's a PR with an example, maybe that is helpful?
https://github.com/robbert-vdh/nih-plug/pull/106

**Comment by Timtam** [comment]
Thank you, I joined the discord and the PR does help with my issue, therefore closing it :).
