### ISSUE TITLE
Host goes OOM when editor is re-opened too many times

### ISSUE THREAD

**Issue by exa04** [robbert-vdh/nih-plug#173]
When a plugin's editor is opened, memory usage increases, but when it's closed, it only slightly decreases. Re-opening the editor a bunch of times can cause many gigabytes of excess memory to be used. Once the plugin is removed, this extra memory is not freed up. Re-opening the GUI too many times causes a crash.

Here's a screencap of Gain GUI (VIZIA) and Gain GUI (egui) causing Ableton Live 12's memory usage to go up.

https://github.com/user-attachments/assets/2b8bbaf5-3330-4be1-afa7-bc2ac93958a5

And here's a screenshot of the Bitwig Studio 5 Plugin Host going out of memory due to this issue - I was spam re-opening the Spectral Compressor (CLAP) editor.

![VS2022 Debugger's Diagnostic Tools showing memory usage increase up to 21 Gigabytes](https://github.com/user-attachments/assets/eba33d03-8fd7-4869-b091-1f116a11912d)

I've seen this happen in Ableton Live 12 and Bitwig Studio 5 on Windows.

**Comment by dathinaios** [comment]
Just tested on Mac Studio M2 on Bitwig and unfortunately I observe the same issue.

**Comment by dathinaios** [comment]
This seems to be a `baseview` issue so I think this can be closed.
