### ISSUE TITLE
Nightly build Error 404 – Not Found (the artifact has expired)

### ISSUE THREAD

**Issue by vincent-vandercruyssen-kunstkaai** [robbert-vdh/nih-plug#175]
https://nightly.link/robbert-vdh/nih-plug/workflows/build/master

I can't seem to download the windows.zip from https://nightly.link/robbert-vdh/nih-plug/workflows/build/master

Error 404 – Not Found

GitHub produced an error for the download of artifact #1825098894.

Usually this means that the artifact has expired (>90 days).

**Comment by robbert-vdh** [comment]
Yeah the last build was three months ago and GitHub removed it. Triggered a new build and added a way to manually regenerate builds if needed again. Thanks for letting me know!
