### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by Jordan-Rowland** [robbert-vdh/nih-plug#19]
Wanted to open a new PR for these, but didn't have access to push a new branch for changes.

> [Crossover](https://github.com/robbert-vdh/nih-plug/blob/master/plugins/crossover) is as boring as it sounds. It **splits cleanly splits** the signal into two to five bands using a variety of algorithms and outputs those through auxiliary outputs so they can be accessed and processed individually. Meant as an alternative to Bitwig's Multiband FX devices but with cleaner crossovers and a linear-phase option.

`splits cleanly splits`

**Comment by robbert-vdh** [comment]
Oh thanks! Fixed.
