### ISSUE TITLE
Smoothing code is quite expensive

### ISSUE THREAD

**Issue by BillyDM** [robbert-vdh/nih-plug#20]
Looking through the code, it appears that this if statement is executed every single frame for every single parameter:

https://github.com/robbert-vdh/nih-plug/blob/master/src/param/smoothing.rs#L198

It would be better if somehow this if statement is only executed once per parameter per process cycle.

I still vouch for baseplug's method which is to fill a buffer with smoothed values for each parameter beforehand. I can help you with it if you want.

https://github.com/wrl/baseplug/blob/trunk/src/smooth.rs#L47

**Comment by BillyDM** [comment]
Baseplug's method also makes it easier and more optimized for block-based processing, which we should encourage users to do anyway.

**Comment by robbert-vdh** [comment]
The linear and logarithmic smoothing are cheaper than baseplug's first order low-pass filter (which is also available in NIH-plug with the exponential smoothing style). And you can do block smoothing with the `Smoother::smooth_block` methods. Check out the poly mod example.

**Comment by BillyDM** [comment]
Ah okay, I missed the part where smoothing in blocks only invokes `self.next()` while the parameter is smoothing.

**Comment by BillyDM** [comment]
Hmm, I'm still not a fan of this line:

https://github.com/robbert-vdh/nih-plug/blob/master/src/param/smoothing.rs#L277

Though I suppose it can be worked around by calling `self.is_smoothing()` first.

Yeah, I think this can work for me. Thanks for the clarification!

**Comment by BillyDM** [comment]
Although wait, have you actually measured it to see if it's faster?

In baseplug's smoother, the hot part (the lowpass filter) is this loop:
```rust
for i in 1..nframes {
    self.output[i] = input + (self.output[i - 1] * self.b);
}
```

And in your code, because it is invoking `self.next()` here:
https://github.com/robbert-vdh/nih-plug/blob/master/src/param/smoothing.rs#L276
the loop actually functions like this:
```rust
block_values[..num_smoothed_values].fill_with(|| {
    if self.steps_left.load(Ordering::Relaxed) > 0 {
            let current = self.current.load(Ordering::Relaxed);
            let target = self.target.to_f32();

            let old_steps_left = self.steps_left.fetch_sub(steps as i32, Ordering::Relaxed);
            let new = if old_steps_left <= steps as i32 {
                self.steps_left.store(0, Ordering::Relaxed);
                target
            } else {
                match &self.style {
                    SmoothingStyle::Linear(_) => current + (self.step_size * steps as f32),
                    ...
                }
            };
            self.current.store(new, Ordering::Relaxed);

            T::from_f32(new)
        } else {
            self.target
        }
    }
});
```

To me it looks like you're doing more instructions per sample than baseplug (at-least two if-statements executed per-sample), even with compiler optimizations.

**Comment by robbert-vdh** [comment]
Did you profile and found this to be a bottleneck? The block smoothing can be optimized by directly computing the smoothing steps instead of calling `next()` a couple times, but I'd be very surprised to see this come up as a hot spot in your profiling results.

**Comment by BillyDM** [comment]
All I'm saying is that this can be greatly optimized by not calling `self.next()` in the block smoothing methods.

**Comment by BillyDM** [comment]
I really want to avoid running if-statements per-sample when possible. Especially when it's an if-statement per sample per parameter.
