### ISSUE TITLE
Possible to use DISTRHO's travesty bindings for VST3?

### ISSUE THREAD

**Issue by luciascarlet** [robbert-vdh/nih-plug#21]
Hi, I'm not sure if this is the right place to ask, but I wonder whether it would be feasible to use DISTRHO/DPF's `travesty` bindings for VST3 support instead of `vst3-sys`. `travesty` is a pure C interface to VST3 that is liberally licensed (ISC licence), unlike `vst3-sys` which is GPLv3 due to its reliance on Steinberg's dual-licensed SDK, so that should be preferable for the MIT licensing model on nih-plug if anyone wishes to build commercial plugins with it. They can be found here: https://github.com/DISTRHO/DPF/tree/df6d7f50377266b1869c6c590ff7412d2241856e/distrho/src/travesty

Unfortunately there isn't really much documentation for this, but DPF itself could be used as a reference I imagine, as it does itself use `travesty` to provide its VST3 support. Cardinal (also by DISTRHO) is a popular plugin built with DPF, and I can personally confirm that the VST3 build works well. I'd love to hear your thoughts and whether you think it would be reasonable to implement here.

**Comment by robbert-vdh** [comment]
No, that won't happen. I may or may not know where those bindings originated from, and they are exactly as legal as relicensing the vst3-sys crate as MIT or ISC would be. APIs are in theory not copyrightable under both EU and US law, but I really don't want want to take Steinberg to court on order to prove that. NIH-plug also supports [CLAP](https://github.com/free-audio/clap), which is liberally licensed and developed by the plugin and host developers who are using the API. There is ongoing effort on making new Rust VST3 bindings that are directly generated from the C++ interfaces and could thus avoid the licensing GPLv3-only licensing problems that way (i.e., you'd be able to sign the VST3 license and use them under that license), but those bindings don't exist yet. NIH-plug will switch to them once they become available.

**Comment by luciascarlet** [comment]
Ah, that makes sense. Thanks for the explanation, I really appreciate it!
