### ISSUE TITLE
assert_process_allocs does not affect standalone.

### ISSUE THREAD

**Issue by magnetophon** [robbert-vdh/nih-plug#29]
Thanks for creating ``assert_process_allocs``, it's exactly the kind of thing I need to prevent me from shooting myself in the foot!  :grinning: 

It seems it doesn't apply to the standalone version though.
Any chance of adding it there as well?

**Comment by robbert-vdh** [comment]
Good catch, I've added it in 997249a293331b9fae42c562d1c050e3504305cb. Also noticed that the call to `reset()` was missing in the standalones so I also added that in the commit before this.

**Comment by magnetophon** [comment]
Works as advertised!
