### ISSUE TITLE
Implementing the Param trait

### ISSUE THREAD

**Issue by sleiner** [robbert-vdh/nih-plug#41]
## Use case + Background info

I have recently come upon a few use cases where I found that the `Param` implementations included with `nih-plug` are not super well-suited, so I wanted to implement a custom `Param`.

However, I found a few things that I did not expect: The `as_ptr` method requires me to construct a `ParamPtr` instance, which is not possible for fully custom implementations since the possible types of parameters are hard-coded in `nih-plug`. Still, as I was delegating a bit of my `Param`s basic functionality to an `IntParam` anyway, I could return something like `self.inner.as_ptr()` here.

Next, I found that a few methods from my `Param` implementation were never called (`normalized_value_to_string`, `string_to_normalized_value`). As far as I see, these are only ever called through `ParamPtr` - so even though I have to provide these functions, they are never used. For my concrete case, I could also hack around this by customizing my underlying `IntParam` using `with_value_to_string` and `with_string_to_value`.

## The actual questions

Implementing `Param` out-of-tree seems rather unergonomic to me. Am I missing some obvious alternative here? Is this currently an intended use of `Param` at all?

**Comment by robbert-vdh** [comment]
`Param` can indeed not be implemented outside of NIH-plug itself. What kind of parameter do you need that is not covered by the current parameter types? (`FloatParam`/continuous values, `IntParam`/discrete values, `BoolParam`/discrete boolean values, and `EnumParam<T>`/discrete values representing the enum `T`)

**Comment by sleiner** [comment]
I'm currently trying to build a _delay time_ parameter that can switch between two modes:
- free (as in "milliseconds") → continuous values
- synced (as in note durations, like dotted quarter) → basically an enum

**Comment by robbert-vdh** [comment]
Plugins usually take one of the following two options here:

- Use a single `FloatParam` with a 0-1 range alongside a boolean to indicate whether the tempo sync mode is enabled. This could be an `AtomicBool` set by a callback on a `BoolParam`. Depending on the value of that boolean, your text-to-value and value-to-text conversions either show a time in milliseconds or a tempo synced time. And in your process function you also convert the `[0, 1]` value to the correct format based on that boolean.
- Use two parameters, one for milliseconds and one for tempo synced intervals. The third boolean parameter determines which one is shown in the GUI and used in the processing function.

**Comment by sleiner** [comment]
Thanks for explanation! 😊 I am aware of those possibilities (and given that the plugins I am working on will not have a GUI, I'm probably going with something like the first option that you outlined).
Nevertheless, I would really like to encapsulate this in a clean abstraction, especially since this will be reused across multiple plugins. And at least from my plugin author perspective, a `Param` implementation with an expressive `Plain` type would be great for that. At the same time, this setup is (in my opinion, at least) much too specific to include into `nih-plug` itself.

So I'm wondering what your stance is on letting users implement their own `Param`s? (say, on the spectrum of _I'll drop everything and implement it right now_ **to** _not really on the roadmap, but open to contributions_ **to** _this is an anti-pattern, I do not want this feature to be part of `nih-plug` now or in the future_) 😄

**Comment by robbert-vdh** [comment]
You really don't need a dedicated `Param` implementation for this. That won't solve any of the issues I described above, and it would only make things more complicated. If you want to encapsulate this behavior because you're going to use in in a bunch of different places, then simply define struct to abstract around this with one or two `FloatParam`s and a `BoolParam` like I described. Add a method to get the time value in samples or milliseconds based on that boolean's value, add simple parameter `#[id = "..."]`s on the parameter fields, and then `#[derive(Params)]` on that struct. You can then reuse that struct multiple times in your main parameter struct by using the `#[nested(id_prefix = "delay_l", group_name = "Delay L")]` [attribute](https://nih-plug.robbertvanderhelm.nl/nih_plug/params/trait.Params.html#nestedid_prefix--foo-group_name--foo) with different ID prefixes/group names (the group names are optional, they're only for display purposes in certain DAWs).

**Comment by sleiner** [comment]
I had not thought about nesting to solve this... That is a really nice solution for that problem, thanks! 🙌

**Comment by robbert-vdh** [comment]
So as one final tip, if you store that `BoolParam` in the wrapper struct as an `Arc<BoolParam>`, you can directly use its value inside of your text<->value callbacks if you're going with the single normalized `FloatParam` approach.

**Comment by sleiner** [comment]
Thanks :-) I have been toying around with that approach and it works really well 😊
