### ISSUE TITLE
More percise Buffer::len documentation.

### ISSUE THREAD

**Issue by SiebenCorgie** [robbert-vdh/nih-plug#47]
Hi, 

I just stumbeled uppon a minor issue in the documentation of [Buffer::len](). It says:
> Returns the number of samples in this buffer.

While trying to implement my own time tracking I thought something like this should get me the "time the buffer occupies"
```
let buffer_time_len = (buffer.len() / buffer.channel()) as f32 / transport.sample_rate;
```
The reasoning being: If `buffer.len()` is the number of samples in the buffer, I got `len/num_channels` samples per channel.

However, `buffer.len()` actually returns *number of samples per channel*. So it might be good to include that information in the docs. Something like this:

> Returns the number of samples per channel in this buffer. 

Cheers!

**Comment by robbert-vdh** [comment]
I'll change it, but I really don't think it's needed. This follows the usual definition of an audio buffer. The only time where a buffer's size may incorporate the channel count is when dealing with interleaved audio, and audio software doesn't use interleaved audio for DSP. Just like if you configure your audio interface to use a buffer/period size of 512 samples, you'll need to output 512 samples _per channel_. A buffer size of 512 samples on an 8 output audio interface doesn't mean you process audio in chunks of 64 samples.
