### ISSUE TITLE
VST3 com interface issue / fix

### ISSUE THREAD

**Issue by PolyVector** [robbert-vdh/nih-plug#58]
Hello,
I found an issue with the VST3 com interface where any calls to create_instance() appear to return an IComponent, ignoring the IID that was requested.  Typically this isn't a problem as the IComponent requested first, but the Steinberg AUWrapper requests an IAudioProcessor first, which wreaks havoc.  For example, calls to audioProcessor->setProcessing() actually invoke get_bus_info() with nonsensical parameters.  This was pretty difficult to figure out!

The vst3-sys project seems aware of this which I assume is why macros require IComponent to be listed first.  Related issue for reference: https://github.com/RustAudio/vst3-sys/issues/14

Here's a quick-and-dirty fix in **wrapper/vst3/factory.rs**.  I'm sure there's a better way to do this, but I'm new to Rust.
```
    unsafe fn create_instance(
        &self,
        cid: *const vst3_sys::IID,
        iid: *const vst3_sys::IID,
        obj: *mut *mut vst3_sys::c_void,
    ) -> tresult {
        check_null_ptr!(cid, obj);

        if (*cid).data != P::PLATFORM_VST3_CLASS_ID {
            return kNoInterface;
        }

        //Fix: Returns the requested interface:
        let wrapper = Box::into_raw(Wrapper::<P>::new());
        if (*wrapper).query_interface(iid, obj) == vst3_com::sys::NOERROR {
            kResultOk
        } else {
            kResultFalse
        }
    }
```

Thanks for the wonderful work you're doing on NIH-plug, I'm really loving the combo with egui. 🍻

**Comment by robbert-vdh** [comment]
That's an oversight on my part, sorry! Don't know how I missed this, normally I'm super thorough with these kinds of things. I fixed this in a97c8ea554617c6a8e88e00375a51ef4c0e570b8. The caller can now properly create a properly object for any interface supported by the plugin.
