### ISSUE TITLE
[NIH-PLUG+EGUI] How to scale interface? egui_ctx.set_pixels_per_point(2.0) has no effect.

### ISSUE THREAD

**Issue by oiwn** [robbert-vdh/nih-plug#59]
Hi there. I'm pretty new in Rust and audio in general. 

Recently i made simple app in egui - calculator, and able to do interface scaling through

`egui_ctx.set_pixels_per_point(5.0);`

works fine.

So i tried same in egui+nih-plug: 

```Rust
        create_egui_editor(
            self.params.editor_state.clone(),
            (),
            |_, _| {},
            move |egui_ctx, setter, _state| {
                egui::CentralPanel::default().show(egui_ctx, |ui| {
                    // TODO: this is not working 
                    egui_ctx.set_pixels_per_point(5.0);
                    // configure_text_styles(egui_ctx);

```

And it's do not has visible changes. What i'm doing wrong?

**Comment by robbert-vdh** [comment]
`egui_baseview` would need to support scaling first. I added the functionality needed for that to baseview, but noone really uses `egui_baseview` so that would need to be updated to support it first (and it needs to be updated in general).

**Comment by oiwn** [comment]
ah got it. 

Is there fundamental difference between ```baseview``` and ```eframe```?

**Comment by robbert-vdh** [comment]
Eframe uses winit for window creation. Anyways, this is not a NIH-plug issue so I'll close this. Feel free to create an issue on the egui_baseview if you want to see this get fixed.
