### ISSUE TITLE
Parameter inconsistency on startup with VST3 host

### ISSUE THREAD

**Issue by fitzthum** [robbert-vdh/nih-plug#64]
First of all, this is a great project. Thanks for building something hat can set so much creativity in motion. 

I've noticed that on startup the parameter values reported by my VST3 host do not match the internal state of the plugin. As in, the nob on the host will be set to zero, but the plugin will clearly have a different value. As soon as I touch the nob things get in sync. This is true for the gain example as well as Diopser and the project that I am starting on. I have also noticed that the plugin host reports that the plugin has zero parameter inputs.

I have been using Carla as VST host, which seems to work fine, although it took me a while to realize that you have to set your VST3 path to the `bundled` directory or the plugins won't be found. (You also have to close the scanning window before new plugins will show up in the list). I am open to an alternative host if anyone has a recommendation.

Bonus question: It seems like `Buffer` always contains `f32`s. Is there any support for `f64` there?

**Comment by robbert-vdh** [comment]
> As in, the nob on the host will be set to zero...

Those are all (very old, at this point) Carla bugs. And probably also JUCE plugin host bugs. Waveform shares many of these bugs. NIH-plug is definitely working correctly.

> Bonus question: It seems like Buffer always contains f32s. Is there any support for f64 there?

There is not. There's no benefit to running the audio graph at double precision.
