### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by Aries85** [robbert-vdh/nih-plug#66]
Hello there,
    is it possible to have keyboard input for plugins?
    
Tried with VST3 and egui in REAPER, however I was only able to get several special characters - [;
Tried also REAPER's option *Send all keyboard input to plugin*.
Tried building the examples to test, however they don't seem to have place for keyboard input (or maybe I missed that).

Is there any special setup for keyboard input required? Tried requiring the focus on egui, however still no luck.

**Comment by robbert-vdh** [comment]
Baseview (the underlying windowing library) does not yet have any kind of keyboard input focus handling. So you get whatever events you get.
