### ISSUE TITLE
Headless build

### ISSUE THREAD

**Issue by laenzlinger** [robbert-vdh/nih-plug#69]
I am new to nih-plug. To me this project looks very interesting. I was able to build a CLAP plugin for Reaper in a few hours including some small UI. Thats very cool, thanks for all your valuable work.

My next experiment was to build a VST3 plugin to run on Elk Audio OS (completly headless). I dont need any UI for this plugin.

However, already when building (the starting point was the examples/gain plugin) I recognised that there are dependencies to X11. I first thought its just for the standalone version, but when I tried to run the plugin in the target system I got the following error:

```
[2023-03-30 17:49:41.871] [error] [vst3] Failed to load VST3 Module: dlopen failed.
libxcb.so.1: cannot open shared object file: No such file or directory
```

Can I use some build flags to completely remove the X11 or any other UI dependencies?

Many thanks

**Comment by robbert-vdh** [comment]
The gain plugin has no dependency on xcb. You're probably looking at the wrong plugin, like one of the `gain_gui_*` plugins.

**Comment by laenzlinger** [comment]
Thanks Robbert, I have figured out now what was the problem

I had the standalone feature inabled on nih_plug

```
-nih_plug = { git ="https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs", "standalone"] }
+nih_plug = { git ="https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
```

After removing it the resulting vst plugin also did not contain the x11 dependencies anymore.
