### ISSUE TITLE
FL Studio problem + some SPECTRAL COMPRESSOR suggestions

### ISSUE THREAD

**Issue by fafayqa** [robbert-vdh/nih-plug#70]
When I load your VST3 versions into FL Studio 12 (on Win 10 x64) most of them (except 3) show no GUI at all, so they are useless.

ON THE OTHER HAND, I am totally blown off by your SPECTRAL COMPRESSOIR which is the only one to my knowledge that supports both downward and upward compression at the same time and does it without artifacts (the only other one is that internal Cubase Pro 12 plug but it is basically useless, very bad plug although it comes from Steinberg, believe it or not!) + it contains such unique parameters that it makes me thrilled even to tweak them (haha) so it might become one of my most beloved comps!

**FLOOR VALUE FOR THE UPWARD COMP** (which I actually never saw on any upward compressor, wondering why in the world?!), so that one can tell OK, does not upward anything below specific level (basically low-end limit so that it would avoid upwarding hiss and hum) - what do you think, could you implement it?

**INPUT PARAMETER VALUES MANUALLY BY KEYBOARD TYPING**, not just ad hoc with the mouse (when I double left click the parameter value it just resets to defaults instead of becoming input filed where one could type the desired parameter value + I also tried CTRL, ALT, SHIFT combination...nothing, well actually by ALT+LMB it seems the value becomes selectable but not changeable - typing does nothing, it only selects the value).

**INITIALIZE PLUGIN WITH THIS PARAMETERS**: this would make any new instance automatically load such by default, it would replace its internal default values - would be quite handy so one does not need to do repetitive tasks all the time (sure, I know I can save it as preset, but still it is several clicks more compared to default values loaded immediately with the plug instance being loaded into fx slot :-D).

**BYPASS BUTTON** would be great too, to have it - as other plugs do - inside its GUI (I see you have MIX value there which is really great, but why do I need to constantly setting mix to 0% only to hear the difference without the plug, right?).

**HOST SYNC FOR INDIVIDUAL VALUES** - each individual parameter should have its own SYNC option, meaning you could select this for some parameters, while others would stay as normal (that is when option SYNC is enabled values in milliseconds would turn into 1/1, 1/2, 1/4, 1/8 etc.): it would be great to have this implemented, so that we can all "ins" ands "outs" nicely "pump" with the actual tempo without us manually trying to hit the right value. Like having HOST SUNC for Attack and Release would make things much much much easier to adjust than actual simple numeric value, right?

**Comment by ardura** [comment]
I've also run into this issue where the exported VST3 works in Reaper or Bitwig, but not in FL Studio. I haven't been able to debug it further yet but when comparing with the clap-wrapper I got the CLAP to VST3 version of my plugin working. I'll try to capture some more info about why this is happening in FL when I get a chance.
