### ISSUE TITLE
Subtle eroding of velocity values (CLAP only)

### ISSUE THREAD

**Issue by ijijn** [robbert-vdh/nih-plug#84]
Hi again folks!

I recently noticed a weird thing, after much scratching of the head, that whenever I put an nih-plug CLAP plugin on a track, processed MIDI events would generally decrease their velocity by a small amount: most notes would lose 1 "point" of velocity per instance, while some would remain unchanged. Other details, such as CC values, were unaffected, however. For reference, this was with the latest Reaper version on Windows 11, even for plugins that do _absolutely nothing_ to the MIDI (see the bottom of this post for a quick example).

I tried the equivalent VST3 builds and everything was fine. I considered that this could be a fault in Reaper's handling of CLAP, but I downloaded another CLAP plugin to see (namely, Ny by Full Bucket Music) and that one's MIDI-thru worked perfectly.

After this initial round of testing, I thought that maybe there was a calibration error between the velocity values of nih-plug and CLAP, and that does indeed seem to be the case: as far as I can tell, CLAP's `f64` velocities operate on a range from 0.0 (0) to 1.0 (128) (i.e. `value / 128.0`) whereas here we use `value / 127.0` for our `f32`s (EDIT: oops, wrote that backwards before). In any case, I patched the velocity conversion logic and the problem went away completely, working across the full range of inputs. A pull request is incoming with these minor changes for consideration.

Thanks as always and all the best,
Iain

```rust
use std::sync::Arc;

use nih_plug::prelude::*;

#[derive(Default, Params)]
pub struct PluginParams {}

#[derive(Default)]
pub struct Stub {
    params: Arc<PluginParams>,
}

impl Plugin for Stub {
    const NAME: &'static str = "stub";
    const VENDOR: &'static str = "stubby stubbins";
    const URL: &'static str = "[stub.org](http://stub.org/)";
    const EMAIL: &'static str = "[stubby@stub.org](mailto:stubby@stub.org)";
    const VERSION: &'static str = env!("CARGO_PKG_VERSION");
    const AUDIO_IO_LAYOUTS: &'static [AudioIOLayout] = &[];
    const MIDI_INPUT: MidiConfig = MidiConfig::MidiCCs;
    const MIDI_OUTPUT: MidiConfig = MidiConfig::MidiCCs;
    const SAMPLE_ACCURATE_AUTOMATION: bool = true;

    type SysExMessage = ();
    type BackgroundTask = ();

    fn params(&self) -> Arc<dyn Params> {
        self.params.clone()
    }

    fn process(
        &mut self,
        _buffer: &mut Buffer,
        _aux: &mut AuxiliaryBuffers,
        context: &mut impl ProcessContext<Self>,
    ) -> ProcessStatus {
        while let Some(event) = context.next_event() {
            context.send_event(event);
        }

        ProcessStatus::Normal
    }

    fn editor(&mut self, _async_executor: AsyncExecutor<Self>) -> Option<Box<dyn Editor>> {
        None
    }

    fn initialize(
        &mut self,
        _audio_io_layout: &AudioIOLayout,
        _buffer_config: &BufferConfig,
        _context: &mut impl InitContext<Self>,
    ) -> bool {
        true
    }
}

impl ClapPlugin for Stub {
    const CLAP_ID: &'static str = "org.stub.stubby";
    const CLAP_DESCRIPTION: Option<&'static str> = None;
    const CLAP_MANUAL_URL: Option<&'static str> = None;
    const CLAP_SUPPORT_URL: Option<&'static str> = None;
    const CLAP_FEATURES: &'static [ClapFeature] = &[ClapFeature::NoteEffect, ClapFeature::Utility];
}

impl Vst3Plugin for Stub {
    const VST3_CLASS_ID: [u8; 16] = *b"stubstubstubstub";
    const VST3_SUBCATEGORIES: &'static [Vst3SubCategory] =
        &[Vst3SubCategory::Instrument, Vst3SubCategory::Tools];
}

nih_export_clap!(Stub);
nih_export_vst3!(Stub);
```

**Comment by robbert-vdh** [comment]
See my comment in the PR: https://github.com/robbert-vdh/nih-plug/pull/85#issuecomment-1722259236
