### ISSUE TITLE
Updating to Latest Vizia

### ISSUE THREAD

**Issue by ejjonny** [robbert-vdh/nih-plug#87]
I'm interested in bringing nih-plug's Vizia dependency up to date. 
I'm not sure how large of an undertaking this actually is, as the [fork](https://github.com/robbert-vdh/vizia/tree/patched) does not seem to have large changes.

I've gotten things compiling with the latest Vizia but I'm stumped here & looking for leads. The GUI is unresponsive in standalone mode as the majority of the CPU time is spent in this stack trace re-styling the interface.

Any thoughts on what I might be missing here?

Let me know if there is a better way for me to get input on this issue. I would love to be able to use the latest Vizia as the patched fork is quite far behind main.

```
20432	crisp (60668)	
17306	Main Thread  0x5f8225	
17306	start	
17306	main	
17306	std::rt::lang_start::h529363aee13a6c62	
17306	std::rt::lang_start_internal::h434fe84e11a92429	
17306	std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h11ab781115c04bcf	
17306	std::sys_common::backtrace::__rust_begin_short_backtrace::h4a882756e564a802	
17306	core::ops::function::FnOnce::call_once::h2586012a7f0b7b1b	
17306	crisp::main::h90babba28b85b71c	
17306	nih_plug::wrapper::standalone::nih_export_standalone::h6392a52de9779039	
17306	nih_plug::wrapper::standalone::nih_export_standalone_with_args::h79bb98ca4ce11711	
17306	core::result::Result$LT$T$C$E$GT$::or_else::h55aafd6c10fd263b	
17306	nih_plug::wrapper::standalone::nih_export_standalone_with_args::_$u7b$$u7b$closure$u7d$$u7d$::h16f8cbb54676226d	
17306	nih_plug::wrapper::standalone::run_wrapper::hd2d70150e7a8e42b	
17306	nih_plug::wrapper::standalone::wrapper::Wrapper$LT$P$C$B$GT$::run::h2699ffd24d47e27d	
17306	baseview::window::Window::open_blocking::h97a50e827f25e1e8	
17306	baseview::macos::window::Window::open_blocking::h9de9916bf8a48644	
17306	_$LT$$BP$mut$u20$objc..runtime..Object$u20$as$u20$cocoa..appkit..NSApplication$GT$::run::hcf2921796ce7adf6	
17306	objc::message::platform::send_unverified::h188f516897c74c44	
17306	_$LT$$LP$$RP$$u20$as$u20$objc..message..MessageArguments$GT$::invoke::hdc27c3db03cbd3c0	
17306	-[NSApplication run]	
17306	-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]	
17306	_DPSNextEvent	
17306	_BlockUntilNextEventMatchingListInModeWithFilter	
17306	ReceiveNextEventCommon	
17306	RunCurrentEventLoopInMode	
17306	CFRunLoopRunSpecific	
17306	__CFRunLoopRun	
17229	__CFRunLoopDoTimers	
17227	__CFRunLoopDoTimer	
17222	__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__	
17222	baseview::macos::window::WindowState::setup_timer::timer_callback::h9e4ee84e7fbf4037	
17222	baseview::macos::window::WindowState::trigger_frame::h3dd68f6ccda1a5d0	
17221	_$LT$vizia_baseview..window..ViziaWindow$u20$as$u20$baseview..window..WindowHandler$GT$::on_frame::h1a1fc8d766fd72d1	
10337	vizia_baseview::application::ApplicationRunner::on_frame_update::h65619d0115cd22fb	
10294	vizia_core::context::backend::BackendContext::process_style_updates::haf29c635292cebcf	
10182	vizia_core::systems::style::style_system::hee4b9919174c6c43	
9754	vizia_core::systems::style::compute_matched_rules::hd8b4f574bed92254	
7281	selectors::matching::matches_complex_selector_internal::h3d8404151ab26811	
4885	selectors::matching::matches_compound_selector::h13237745c6db8ca5	
2164	selectors::matching::matches_local_name::h8a01d9d0d78049ee	
2117	_$LT$vizia_core..systems..style..Node$u20$as$u20$selectors..tree..Element$GT$::has_local_name::h57341f2f2946c5f4	
1725	std::collections::hash::map::HashMap$LT$K$C$V$C$S$GT$::get::h1a1edbd6698661a2	
1680	hashbrown::map::HashMap$LT$K$C$V$C$S$C$A$GT$::get_inner::h22b60ea0b1e1cdc1	
924	hashbrown::raw::RawTable$LT$T$C$A$GT$::get::h44d87ba416aec045	
885	hashbrown::raw::RawTable$LT$T$C$A$GT$::find::h486693bb02b42787	
427	hashbrown::raw::RawTable$LT$T$C$A$GT$::find::h486693bb02b42787	
275	hashbrown::raw::RawTableInner$LT$A$GT$::find_inner::h3a3fe0b13719c4b6	
```

**Comment by ejjonny** [comment]
Here are my modifications for reference:
https://github.com/vizia/vizia/compare/main...ejjonny:vizia:e/update?expand=1
https://github.com/robbert-vdh/nih-plug/compare/master...ejjonny:e/update?expand=1

**Comment by robbert-vdh** [comment]
There's a fork here that does most of the styling, but it suffers from the same problems you mentioned: https://github.com/geom3trik/nih-plug/commit/122c668e6f4211fb0eb6cf3cd0cb37c259a846f6

I started work on the branch you linked but I quickly realized that it would probably be best to wait for Vizia to stabilize again and for the kinks to get ironed out, instead of potentially having to do this work twice. The issues I remember that would need to be fixed on Vizia's side are the nonfunctional interaction thing you mentioned, some positioning things not yet being implemented after the styling system change requiring workarounds everywhere, a regression in the font handling (you can no longer refer to e.g. `Noto Sans Light` by name), some of the resizing behavior not working, and Spectral Comrpessor not drawing correctly (I only checked that plugin for now).

**Comment by ejjonny** [comment]
Oh, good to know! Looks like the unresponsive UI is reproducible in vizia's example apps so I've opened an issue [there](https://github.com/vizia/vizia/issues/420).
