### ISSUE TITLE
KeyEvents not received on windows

### ISSUE THREAD

**Issue by rbmj** [robbert-vdh/nih-plug#90]
On my Debian machine, I'm able to process key events with the following code:

```
for evt in i.events.iter() {
    if let egui::Event::Key{key, pressed, repeat, ..} = evt {
        //Do stuff
    }
}
```

This does not work on windows.  I've confirmed with `nih_log!()` that there are no actual key events to process.  Any thoughts on why the plugin is receiving events on one platform but not the other?  I've run it both in standalong JACK mode and as a plugin under Carla with the same behavior.

**Comment by robbert-vdh** [comment]
That's a `baseview`/`egui_baseview` issue. Baseview currently does not have any keyboard input handling.
