### ISSUE TITLE
Fail to build diopser, spectral_compressor

### ISSUE THREAD

**Issue by willsbit** [robbert-vdh/nih-plug#91]
I'm having trouble building Diopser. `cargo xtask bundle gain --release` is running fine, but `cargo xtask bundle diopser --release`  gives:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:86:39
   |
86 | #![cfg_attr(feature = "simd", feature(portable_simd))]
   |                                       ^^^^^^^^^^^^^

```

So I tried `cargo +nightly xtask bundle diopser --release` , but that gives me some linker errors:
```
  = note: /usr/bin/ld: cannot find -lxcb-icccm: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `diopser` (lib) due to previous error
Error: Could not build diopser
```
The same thing happens with `spectral_compressor`.

I'm on Fedora 39. I installed `libXcm-devel` and some other packages I thought could solve this, but it didn't help.

**Comment by robbert-vdh** [comment]
>   = note: /usr/bin/ld: cannot find -lxcb-icccm: No such file or directory

You need to install `libxcb-icccm`. The package is probably called `xcb-icccm-devel` or something like that on Fedora.

**Comment by willsbit** [comment]
Finally found it, it's the `xcb-util-wm-devel` package that needs to be installed.

Link to Fedora RPM: https://fedora.pkgs.org/38/fedora-x86_64/xcb-util-wm-devel-0.4.2-2.fc38.x86_64.rpm.html
