### ISSUE TITLE
Memory leak when opening and closing plugin window

### ISSUE THREAD

**Issue by yan-h** [robbert-vdh/nih-plug#93]
Every time I close and reopen a plugin's window, its plugin host process in Bitwig uses more memory, resetting only on deactivating or deleting the plugin instance.  I can increase the memory footprint indefinitely by repeatedly opening and closing the plugin window. This doesn't happen with any of the non nih-plug plugins that I've tried.

On macOS Sonoma, the memory increase is ~50 mb each time for Diopser, ~40mb for Crisp, and ~10mb for gain_gui_egui. I didn't notice a difference between CLAP and VST3. 

I tested Diopser on Windows 11 as well, and the leak was much smaller: ~2mb each time.

**Comment by maxjvh** [comment]
on macOS there is a bug in [baseview](https://github.com/RustAudio/baseview/) that doesn't release the view instance on closing the UI. afaik this has nothing to do with nih-plug.

**Comment by robbert-vdh** [comment]
This is indeed a baseview bug. I'll see if I can fix some last remaining bugs in Vizia and then finish and merge the `vizia-update` branch today. That should also resolve this issue.

**Comment by robbert-vdh** [comment]
The `vizia-update` branch has now been merged into master, so this should now be resolved for Vizia (other GUI frameworks will need to be updated first).
